version: '2'
services:
  spark:
    image: spark:2.1.1
    volumes:
      - ./spark-app/build/libs:/app
      - ./spark-app/script:/script
      - ./out:/out
    environment:
        - MASTER=spark://172.18.0.2:7077
    ports:
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    command: sleep infinity
